config/routes.rb
FormDyno::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :dynos, only: [:new, :create, :index]
  resources :task_fields, only: [:new, :create]

  root 'static_pages#home'
  match 'auth/:provider/callback', to: 'sessions#fbcreate',     via: [:get, :post]
  match 'auth/failure',            to: redirect('/'),           via: [:get, :post]
  match '/signup',                 to: 'users#new',             via: 'get'
  match '/signin',                 to: 'sessions#new',          via: 'get'
  match '/signout',                to: 'sessions#destroy',      via: 'get' # HTTP DELETE request specified in the link_to tag.
  match '/help',                   to: 'static_pages#help',     via: 'get'
  match '/about',                  to: 'static_pages#about',    via: 'get'
  match '/price',                  to: 'static_pages#pricing',  via: 'get'
  match '/contact',                to: 'static_pages#contact',  via: 'get'
  match '/task_fields',            to: 'task_fields#new',       via: 'get'

end

app/models/user.rb
=begin

Form Creator/Administrator /Dyno Owner = {
    "email" : "kunapuli09@gmail.com",
    "name" : "krishna",
    "phone" : "7202802571",
    "password" : "password",
    "role" : "OWNER",
    "ObjectId" : "51c25b640364a3b7c24240d2"
  }


Field Staff/Executor /Dyno Executor  {
    "email" : "nlkunapuli@gmail.com",
    "name" : "neha",
    "phone" : "7202802753",
    "password" : "password",
    "role" : "EXECUTOR",
    "ObjectId" : "51c25cf50364a3b7c24240d3"
  }

=end
class User
  include Mongoid::Document  
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword

  field :firstName, type: String
  field :lastName, type: String
  field :email, type: String
  field :password, type: String
  field :phone, type: String
  field :city, type: String
  field :remember_token, type: String
  field :password_digest, type: String

  #has_many :dynos
  before_save { self.email = email.downcase }

	# callback method that creates a remember_token before creating a new user in DB
	#"Method reference" - rails looks for method called create_remember_token
	before_create :create_remember_token

	validates(:firstName, presence: true, length: { maximum: 50 })
	validates(:lastName, presence: true, length: { maximum: 50 })
	validates(:phone, presence: true, length: { minimum: 10, maximum: 10 })
	validates(:city, presence: true, length: { maximum: 20 })

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	## VALID_EMAIL_REGEX is a constant
	## format validation
	validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: true, uniqueness: { case_sensitive: false })
	## Sometimes when user clicks submit in quick succession, duplication can still occur.
	## to avoid this, create a database index on email column.
  has_secure_password validations: false # gets all current password tests to pass, validations false lets password confirmation error to pass.
	validates :password, presence: true, length: { minimum: 6 }

	  def User.new_remember_token
    SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  	end

  	# self allows creation of non-local variable, written to DB.
  	private

  	def create_remember_token
	  self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # invoking signed_in_user method.
  # Filter acts only on edit and update.
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id]) # params used to retrieve user id.
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
       sign_in @user
       flash[:success] = "User was successfully created"
       redirect_to @user
    else
       render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :password, :phone, :city)
    end

  # Before filters
    def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
    end

    # Use callbacks to share common setup or constraints between actions.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

  <%= f.label :firstName %><br>
  <%= f.text_field :firstName %><br>

  <%= f.label :lastName %><br>
  <%= f.text_field :lastName %><br>

  <%= f.label :email %><br>
  <%= f.text_field :email %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <!--<%= f.label :password_confirmation %>-->
  <!--<%= f.password_field :password_confirmation %>-->

  <%= f.label :phone %><br>
  <%= f.text_field :phone %><br>

  <%= f.label :city %><br>
  <%= f.text_field :city %><br>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<div class="container">
  <div class="col-lg-offset-5">
    <%= form_for(@user) do |f| %>
        <%= render 'fields', f: f %>
        </div>
        <div class="well center">
        <%= f.submit "Save Changes", class: "btn btn-lg btn-success" %> |
        <%= link_to 'Show Profile', @user, class: "btn btn-lg btn-primary" %> |
        <%= link_to 'Users', users_path, class: "btn btn-lg btn-primary" %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<h1>Configure
  <span class="icon-user"></span><span class="icon-user"></span><span class="icon-user"></span><span class="icon-list"></span>
</h1>

<table class="table table-hover table-striped table-responsive">
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>City</th>
      <!--<th>Show</th>-->
      <!--<th>Edit</th>-->
      <!--<th>Delete</th>-->
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="warning">
        <td><%= user.firstName %></td>
        <td><%= user.lastName %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.city %></td>
        <!--<td><%= link_to '', user, class: "icon-eye-open"%></td>-->
        <!--<td><%= link_to '', edit_user_path(user), class: "icon-edit"%></td>-->
        <!--<td><%= link_to '', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-trash"%></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<div class="center">
<p><span class="badge">ADD A NEW STAFF</span> member to your group <%= link_to 'Add New Staff', new_user_path, class: "btn btn-lg btn-primary"%> </p>
<br>
<p><span class="badge">ASSIGN A NEW TASK</span> to a staff member&nbsp;&nbsp;&nbsp;<%= link_to 'Add New Dyno', dynos_path, class: "btn btn-lg btn-primary"%> </p>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="container center" style="background-color: slategray">
  <p></p>
  <div class="col-lg-6 col-md-offset-3 panel panel-default">
    <%= form_for(@user) do |f| %> <!--form_for helper takes a block with one variable. |f| for form-->
        <!-- Rails creates form tag using @user; Rails figures that @user is of Class User; Rails knows to construct  form with POST method-->
        <%= render 'fields', f: f %>
        </div>
        </div>
        <div class="well center">
          <%= f.submit "Create my account", class: "btn btn-lg btn-success" %>
        </div>
    <% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="panel panel-info col-lg-offset-5 col-lg-2">
    <div class="panel-heading"><h1>Profile</h1></div>
    <div class="panel-body">
    <p>First name:
      <%= @user.firstName %></p>
    <p>Last name:
      <%= @user.lastName %></p>
    <p>Email:
      <%= @user.email %></p>
    <p>Phone:
      <%= @user.phone %></p>
    <p>City:
      <%= @user.city %></p>
    </div>
  </div>
</div>
<div class="well center">
  <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-lg btn-primary" %> |
  <%= link_to 'Users', users_path, class: "btn btn-lg btn-primary" %>
</div>