config/routes.rb
FormDyno::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :dynos, only: [:new, :create, :index]
  resources :task_fields, only: [:new, :create]

  root 'static_pages#home'
  match 'auth/:provider/callback', to: 'sessions#fbcreate',     via: [:get, :post]
  match 'auth/failure',            to: redirect('/'),           via: [:get, :post]
  match '/signup',                 to: 'users#new',             via: 'get'
  match '/signin',                 to: 'sessions#new',          via: 'get'
  match '/signout',                to: 'sessions#destroy',      via: 'get' # HTTP DELETE request specified in the link_to tag.
  match '/help',                   to: 'static_pages#help',     via: 'get'
  match '/about',                  to: 'static_pages#about',    via: 'get'
  match '/price',                  to: 'static_pages#pricing',  via: 'get'
  match '/contact',                to: 'static_pages#contact',  via: 'get'
  match '/task_fields',            to: 'task_fields#new',       via: 'get'

end

app/models/dyno.rb
#extends TaskField

class Dyno
  include Mongoid::Document
  include Mongoid::Timestamps

  field :assignTo, type: User
  field :owner, type: User
  #Array of FormField
  field :fields, type: Array
  field :template, type: Boolean
  field :parent, type: String

  has_many :taskfields
  validates :assignTo, presence: true
end

=begin

Dyno /Form / Dyno Definition = {
    "ObjectId" : "5154fbfe1a882294c9631a8c",
    "title" : "Cable Installation Form",
    "assignedTo" : "51c25cf50364a3b7c24240d3",
    "owner" : "51c25b640364a3b7c24240d2",
    "parent" : "null",
    "isTemplate" : true,
    "fields" : [
      {
        "name" : "Customer Name",
        "type" : "TEXT",
        "mobile" : false,
        "order" : 1,
        "value" : ""
      },
      {
        "name" : "Repair Date",
        "type" : "DATE",
        "order" : 2,
        "mobile" : false,
        "value" : ""
      },
      {
        "name" : "Repair Description",
        "type" : "TEXT",
        "mobile" : false,
        "order" : 3,
        "value" : ""
      },
      {
        "name" : "Repair Window",
        "type" : "text",
        "mobile" : false,
        "order" : 1,
        "value" : ""
      }
    ]
  }

DynoData /FormData / Dyno =
  {
    "ObjectId" : "5154fbfe1a882294c9631a8c",
    "title" : "Cable Installation Form",
    "assignedTo" : "51c25cf50364a3b7c24240d3",
    "owner" : "51c25b640364a3b7c24240d2",
    "parent" : "5154fbfe1a882294c9631a8c",
    "isTemplate" : false,
    "fields" : [
      {
        "name" : "Customer Name",
        "type" : "TEXT",
        "mobile" : false,
        "order" : 1,
        "value" : "John"
      },
      {
        "name" : "Repair Date",
        "type" : "DATE",
        "order" : 2,
        "mobile" : false,
        "value" : "4/1/2014"
      },
      {
        "name" : "Repair Description",
        "type" : "TEXT",
        "mobile" : false,
        "order" : 3,
        "value" : "Cut short the cable from outside"
      },
      {
        "name" : "Repair Window",
        "type" : "text",
        "mobile" : false,
        "order" : 1,
        "value" : "3PM-7PM"
      }
    ]
  }

=end

app/controllers/dynos_controller.rb
class DynosController < ApplicationController

  before_action :signIn_user, only: [:new, :index]

  def new
    @dyno = Dyno.new
  end

  def index
    @dyno = Dyno.new
    @dynos = Dyno.all
  end

  def create
    @dyno = Dyno.new(task_params)
    if @dyno.save
      flash[:success] = "Dyno was successfully created"
      redirect_to @dyno
    else
      render 'new'
    end
  end

  def task_params
    params.require(:dyno).permit(:assignTo)
  end

  def signIn_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
end

app/views/Dynos/_dynofields.html.erb
<%= render 'task_error_messages' %>

  <%= f.label :assignTo %>
  <%= f.select :assignTo, options_for_select(User.all.collect { |user| [user.firstName + "\t" +user.lastName, user._id] },
                                             :assignTo), :multiple => true, :prompt => 'Select Person', :name => 'dyno[_id][]' %>

app/views/Dynos/_task_error_messages.html.erb
<% if @dyno.errors.any? %>
  <div id="errorExplanation">
    <!--Count returns no.of errors; Pluralize avoid gramatical "1 errors" mistakes-->
    <div class="alert alert-error">
      The form contains <%= pluralize(@dyno.errors.count, "error") %>.
    </div>
    <ul>
    <% @dyno.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/Dynos/index.html.erb
<h1>Dynos<span class="icon-list"></span></h1>
<h2 class="text-danger">Page Under Construction.</h2>
<h2 class="text-info">--- Displays the Created Dynos List --- Allows owners to assign Tasks using an existing Dyno
  ---</h2>
<h2> You have not yet created a Dyno. Create one now.</h2>


<!--<table class="table table-hover table-responsive">-->
<!--<thead>-->
<!--<tr>-->
<!--<th>Assigned To <span class="icon-user"></span></th>-->
<!--</tr>-->
<!--</thead>-->

<!--<tbody>-->
<!--
<% @dynos.each do |task| %>-->
    <!--<tr class="info">-->
    <!--
    <% @doc = User.find_by _id: task.assignTo rescue [] %>-->
    <!--
    <% parsed_String= JSON.parse(@doc.to_json) rescue [] %>-->
    <!--<td><%= parsed_String["firstName"] + "\t"+ parsed_String["lastName"] rescue [] %></td>-->
    <!--</tr>-->
    <!--
<% end %>-->
<!--</tbody>-->
<!--</table>-->

<div class="center">
  <!--<%= image_tag("task3.png", width: 700, id: "center") %>-->
  <%= form_for(@dyno) do |f| %> <!--form_for helper takes a block with one variable. |f| for form-->
      <!-- Rails creates form tag using @dyno; Rails figures that @dyno is of Class Dyno; Rails knows to construct  form with POST method-->
      <%= render 'dynofields', f: f %>
  <% end %>
</div>

<div class="well center">
  <%= link_to "New Dyno", task_fields_path, class: "btn btn-lg btn-success" %>
  <%= link_to "Cancel", dynos_path, class: "btn btn-lg btn-primary" %>
</div>