config/routes.rb
FormDyno::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :dynos, only: [:new, :create, :index]
  resources :task_fields, only: [:new, :create]

  root 'static_pages#home'
  match 'auth/:provider/callback', to: 'sessions#fbcreate',     via: [:get, :post]
  match 'auth/failure',            to: redirect('/'),           via: [:get, :post]
  match '/signup',                 to: 'users#new',             via: 'get'
  match '/signin',                 to: 'sessions#new',          via: 'get'
  match '/signout',                to: 'sessions#destroy',      via: 'get' # HTTP DELETE request specified in the link_to tag.
  match '/help',                   to: 'static_pages#help',     via: 'get'
  match '/about',                  to: 'static_pages#about',    via: 'get'
  match '/price',                  to: 'static_pages#pricing',  via: 'get'
  match '/contact',                to: 'static_pages#contact',  via: 'get'
  match '/task_fields',            to: 'task_fields#new',       via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="foot">
  <small>
    <strong>&copy; StarpathIT 2014</strong>
    <br>Created by Lalith Kumar K V N
  </small>
  <nav>
    <ul id="footerul">
      <li id="footerli"><%= link_to "About", about_path %></li>
      <li id="footerli"><%= link_to "Contact", contact_path %></li>
      <li id="footerli">Visit <a href="http://starpathit.com" target="_blank"> Starpath</a> Website</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Form Dyno", root_path, id:"logo" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Pricing", price_path %></li>

        <% if signed_in? %>
            <li><%= link_to "Dynos", dynos_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, :method => "delete"%>
                </li>
              </ul>
            </li>

        <% else %>
            <!--<li><%= link_to "Help", help_path %></li>-->
            <!-- Takes you to static_pages/help as defined inthe routes-->
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
      <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_ieshim.html.erb
 <!-- // INTERNET EXPLORER  // -->
 <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
 <!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
 <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.js" %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js' %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/ieshim' %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
<%= debug(params) if Rails.env.development? %> <!-- To avoid showing debug info to users of deployed app-->
</body>
</html>